config/routes.rb
Rails.application.routes.draw do
 resources :recipes

 root "recipes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    before_action :find_recipe, only: [:show, :edit, :update, :destroy]
    def index
        @recipe = Recipe.all.order("created_at DESC")
    end

    def show
    end

    def new
        @recipe = Recipe.new
    end

    def create
        @recipe = Recipe.new(recipe_params)

        if @recipe.save
            redirect_to @recipe, notice: "Successfully created new recipe"
        else
            render 'new'
        end
    end
    
    def edit 
    end

    def update 
        if @recipe.update(recipe_params)
            redirect_to @recipe 
        else 
            render 'edit'
        end
    end

    def destroy
        @recipe.destroy
        redirect_to root_path, notice: "Successfully deleted recipe"
    end

    private

    def recipe_params
        params.require(:recipe).permit(:title, :description)
    end

    def find_recipe
        @recipe = Recipe.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb.haml
!!! 5
%html
%head
	%title Recipe App
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags

%body

  %nav.navbar.navbar-default
    .container
      .navbar-brand= link_to "Recipe Box", rooth_path

      %ul.nav.navbar-nav.navbar-right
        %li= link_to "Recipe", new_recipe_path
        %li= link_to "Sign Out", rooth_path

  .container
    - flash.each do |name, msg|
      = content_tag :div, msg, class: "alert"
		= yield

app/views/recipes/_form.html.haml
= simple_form_for @recipe, html: { multipart: true } do |f|
	- if @recipe.errors.any?
		#errors
			%p
				= @recipe.errors.count
				Prevented this recipe froms saving
			%ul
				- @recipe.errors.full_messages.each do |msg|
					%li= msg
	.panel-body
		= f.input :title, input_html: { class: 'form-control' }
		= f.input :description, input_html: { class: 'form-control' }
		


	= f.button :submit, class: "btn btn-primary"

app/views/recipes/edit.html.haml
%h1 Edit Recipe
= render 'form'

app/views/recipes/index.html.haml
- @recipe.each do |recipe|
  %h2= link_to recipe.title, recipe

app/views/recipes/new.html.haml
%h1 New Recipe

= render 'form'

%br/

= link_to "Back", root_path, class: "btn btn-default"

app/views/recipes/show.html.haml
%h1 @recipe.title
%p= @recipe.description

= link_to "Back", root_path, class: "btn btn-default"
= link_to "Edit", edit_recipe_path, class: "btn btn-default"
= link_to "Delete", recipe_path, method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-warning"